---
- name: ensure python environment is set up
  pip: requirements=/home/btl/site/api/requirements.txt virtualenv=/home/btl/python

- name: ensure database user is present
  sudo: true
  sudo_user: postgres
  postgresql_user: name=btl password="{{ item }}" state=present
  with_file:
    - btl_password.txt
- name: ensure database is present
  sudo: true
  sudo_user: postgres
  postgresql_db: name=btl owner=btl encoding='UTF-8' template=template0 state=present
- name: ensure postgis setup script is present
  copy: src=postgis-setup.sh dest=/home/btl/postgis-setup.sh mode=0755
- name: set up postgis
  command: /home/btl/postgis-setup.sh creates=/home/btl/postgis-setup-done
- name: ensure database creds file is present
  template: src=dbcreds.py.j2 dest=/home/btl/site/api/dbcreds.py owner=btl group=btl mode=0640
  with_file:
    - btl_password.txt

- name: ensure unzip is at latest
  apt: pkg=unzip state=latest
- name: ensure division boundary loader script is present
  copy: src=load_division_boundaries.py dest=/home/btl/load_division_boundaries.py mode=0755
- name: load division boundaries
  sudo: true
  sudo_user: btl
  command: /home/btl/python/bin/python /home/btl/load_division_boundaries.py chdir=/home/btl creates=/home/btl/divisions-loaded

- name: ensure rbenv is up to date
  sudo: true
  sudo_user: btl
  git: repo="https://github.com/sstephenson/rbenv.git" dest=/home/btl/.rbenv
- name: ensure ruby-build is up to date
  sudo: true
  sudo_user: btl
  git: repo="https://github.com/sstephenson/ruby-build.git" dest=/home/btl/.rbenv/plugins/ruby-build
- name: ensure ruby is installed
  sudo: true
  sudo_user: btl
  command: /home/btl/.rbenv/bin/rbenv install 2.0.0-p0 chdir=/home/btl creates=/home/btl/.rbenv/versions/2.0.0-p0
- name: ensure bundler is installed
  sudo: true
  sudo_user: btl
  command: /home/btl/.rbenv/versions/2.0.0-p0/bin/gem install bundler chdir=/home/btl creates=/home/btl/.rbenv/versions/2.0.0-p0/bin/bundle
- name: install ruby dependencies
  sudo: true
  sudo_user: btl
  command: /home/btl/.rbenv/versions/2.0.0-p0/bin/bundle install chdir=/home/btl/site creates=/home/btl/.rbenv/versions/2.0.0-p0/bin/haml

- name: ensure nodejs PPA is present
  apt_repository: repo="ppa:chris-lea/node.js" state=present
- name: ensure nodejs is at latest
  apt: pkg=nodejs state=latest update_cache=yes
- name: ensure lessc is at latest
  npm: name=less state=present global=yes

- name: run first build of the site
  sudo: true
  sudo_user: btl
  shell: LANG=en_US.UTF-8 PATH=/home/btl/.rbenv/versions/2.0.0-p0/bin:$PATH rake chdir=/home/btl/site creates=/home/btl/site/site

- name: ensure nginx is at latest
  apt: pkg=nginx state=latest
- name: copy nginx configuration for belowtheline.org.au
  copy: src=nginx-belowtheline.org.au dest=/etc/nginx/sites-available/belowtheline.org.au
  notify:
    - restart nginx
- name: link nginx configuration for belowtheline.org.au
  file: path=/etc/nginx/sites-enabled/belowtheline.org.au state=link src=/etc/nginx/sites-available/belowtheline.org.au
  notify:
    - restart nginx
- name: copy nginx configuration for api.belowtheline.org.au
  copy: src=nginx-api.belowtheline.org.au dest=/etc/nginx/sites-available/api.belowtheline.org.au
  notify:
    - restart nginx
- name: link nginx configuration for api.belowtheline.org.au
  file: path=/etc/nginx/sites-enabled/api.belowtheline.org.au state=link src=/etc/nginx/sites-available/api.belowtheline.org.au
  notify:
    - restart nginx
- name: copy nginx configuration for btl.tv
  copy: src=nginx-btl.tv dest=/etc/nginx/sites-available/btl.tv
  notify:
    - restart nginx
- name: link nginx configuration for btl.tv
  file: path=/etc/nginx/sites-enabled/btl.tv state=link src=/etc/nginx/sites-available/btl.tv
  notify:
    - restart nginx
- name: ensure nginx is running
  service: name=nginx state=started

- name: ensure logs directory is created
  file: path=/home/btl/logs state=directory owner=btl group=btl mode=0755
- name: ensure run directory is created
  file: path=/home/btl/run state=directory owner=btl group=btl mode=0755

- name: ensure ballot daemon script is present
  template: src=unicorn-ballot.sh.j2 dest=/home/btl/unicorn-ballot.sh owner=btl group=btl mode=0755
- name: ensure ballot daemon configuration is present
  copy: src=ballot.rb dest=/home/btl/ballot.rb
- name: ensure ballot daemon init configuration is present
  copy: src=btlballot.conf dest=/etc/init/btlballot.conf
- name: ensure init.d link is present for btlballot
  file: path=/etc/init.d/btlballot src=/lib/init/upstart-job state=link
- name: ensure btlballot is running
  service: name=btlballot state=started

- name: ensure geo daemon script is present
  copy: src=gunicorn-geo.sh dest=/home/btl/gunicorn-geo.sh owner=btl group=btl mode=0755
- name: ensure geo daemon init configuration is present
  copy: src=btlgeo.conf dest=/etc/init/btlgeo.conf
- name: ensure init.d link is present for btlgeo
  file: path=/etc/init.d/btlgeo src=/lib/init/upstart-job state=link
- name: ensure btlgeo is running
  service: name=btlgeo state=started

- name: ensure pdf daemon script is present
  copy: src=gunicorn-pdf.sh dest=/home/btl/gunicorn-pdf.sh owner=btl group=btl mode=0755
- name: ensure pdf daemon init configuration is present
  copy: src=btlpdf.conf dest=/etc/init/btlpdf.conf
- name: ensure init.d link is present for btlpdf
  file: path=/etc/init.d/btlpdf src=/lib/init/upstart-job state=link
- name: ensure btlpdf is running
  service: name=btlpdf state=started

- name: ensure store daemon script is present
  template: src=gunicorn-store.sh.j2 dest=/home/btl/gunicorn-store.sh owner=btl group=btl mode=0755
- name: ensure store daemon init configuration is present
  copy: src=btlstore.conf dest=/etc/init/btlstore.conf
- name: ensure init.d link is present for btlstore
  file: path=/etc/init.d/btlstore src=/lib/init/upstart-job state=link
- name: ensure btlstore is running
  service: name=btlstore state=started
